version: "3.8"

services:
  localstack: 
    image: localstack/localstack
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT= 4566
      - SERVICES=s3,sqs,lambda
    ports:
      - "4566:4566"  # LocalStack Gateway 
    volumes:
      - "${TEMP_DIR:-/tmp/localstack}:/tpm/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"