name: project pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password # Cambia esto por tu contraseña
          MYSQL_DATABASE: testdb # Cambia esto por el nombre de tu base de datos de prueba
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create tables for testing
      run: mysql -h localhost -u root -ppassword testdb < tables.sql
      env:
        MYSQL_ROOT_PASSWORD: password # Cambia esto por tu contraseña
        MYSQL_DATABASE: testdb # Cambia esto por el nombre de tu base de datos de prueba

    - name: Auto Increment Semver Action
      uses: MCKanpolat/auto-semver-action@v2
      id: versioning
      with:
        releaseType: patch 
        incrementPerCommit: false
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Changelog CI
      uses: saadmk11/changelog-ci@v1.1.2
      with:
        release_version: ${{ steps.versioning.outputs.new_version }}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
