name: project pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Auto Increment Semver Action
      uses: MCKanpolat/auto-semver-action@v2
      id: versioning
      with:
        releaseType: patch 
        incrementPerCommit: false
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Changelog CI
      uses: saadmk11/changelog-ci@v1.1.2

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
